app_info:
    name: github.com/godverv/matreshka-be
    version: v0.0.3
    startup_duration: 10s
data_sources: []
server:
    - name: grpc
      port: 50051
      gateway_port: 50052
environment: {}

