app_info:
    name: matreshka-be
    version: v1.0.32
    startup_duration: 10s
data_sources:
    - resource_name: sqlite
      path: ./data/sqlite/matreshka-be.db
      migrations_folder: ./migrations
