app_info:
  name: 'matreshka-be'
  version: 'v1.0.29'
  startup_duration: '10s'
data_sources:
  - resource_name: sqlite
    path: ./data/sqlite/matreshka-be.db
server:
  - name: grpc
    port: 53891
environment: []

