name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - "master"

jobs:
  tag-release:
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    steps:
      - name: Release tag
        id: release
        uses: RedSockActions/release_tag@v1.1.7
        with:
          token: ${{ github.token }}
    outputs:
      tag: ${{ steps.release.outputs.tag }}

  web-release:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: internal/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Minio Deploy
        uses: marverlous811/minio-upload@v1.2.0
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'verv'
          local_path: './dist/*'
          remote_path: '/matreshka/'
          recursive: true

  docker-registry-release:
    if: ${{ needs.tag-release.outputs.tag != '' }}
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    needs:
      - tag-release
      - web-release
    steps:
      - name: Release image
        uses: RedSockActions/release_image@v1.0.20
        with:
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
          REGISTRY_PWD:  ${{ secrets.REGISTRY_PWD }}

  npm-registry-release:
    if: ${{ needs.tag-release.outputs.tag != '' }}
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    needs:
      - tag-release
    steps:
      - name: Release image
        uses: RedSockActions/release_npm_package@v0.0.4
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ needs.tag-release.outputs.tag }}
          WORKING_DIRECTORY: pkg/web
